split:
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1
  target_column: "MeanTemp"
  group_by_month: true
  random_state: 42
  
# ============================================
# ПАРАМЕТРЫ ДЛЯ ЛИНЕЙНЫХ МОДЕЛЕЙ С РЕГУЛЯРИЗАЦИЕЙ
# ============================================
#
# 📌 ТРИ ТИПА МОДЕЛЕЙ:
#   ridge    - L2-регуляризация (уменьшает веса, но не обнуляет)
#   lasso    - L1-регуляризация (может обнулять веса - отбор признаков)
#   elastic  - комбинация L1 + L2 (гибрид)
#
# 📌 КАК НАСТРАИВАТЬ:
#   1. alpha - ЧЕМ БОЛЬШЕ, ТЕМ СИЛЬНЕЕ РЕГУЛЯРИЗАЦИЯ
#      - Слишком большое → модель недообучается (все веса почти 0)
#      - Слишком маленькое → модель переобучается (как обычная регрессия)
#      Обычный диапазон: 0.0001 до 10.0
#
#   2. fit_intercept - добавлять ли свободный член (константу)
#      - True: y = w1*x1 + w2*x2 + ... + b
#      - False: y = w1*x1 + w2*x2 + ... (без b)
#      Обычно True, кроме случаев, когда данные точно центрированы
#
#   3. max_iter - максимальное число итераций для сходимости
#      - Если модель не сходится (warning), увеличить до 5000-10000
#
#   4. l1_ratio (только для elastic) - баланс между L1 и L2
#      - 1.0 = чистый Lasso (L1)
#      - 0.0 = чистый Ridge (L2)
#      - 0.5 = равновесие
#
#   5. positive (для Ridge/Lasso) - только положительные коэффициенты
#      - True: все веса >= 0
#      - False: могут быть отрицательные
#
#   6. tol - точность сходимости (чем меньше, тем точнее, но дольше)
#      Обычно 1e-4 или 1e-3
# ============================================

linear_models:
  # ---------- RIDGE (L2-регуляризация) ----------
  ridge:
    enabled: true                # true/false - включить/выключить модель
    alpha: 1.0                    # сила регуляризации (0.01, 0.1, 1.0, 10.0)
    fit_intercept: true           # добавлять свободный член
    positive: false               # только положительные коэффициенты
    max_iter: 1000                 # макс. итераций (увеличить если не сходится)
    tol: 0.0001                    # точность сходимости
    solver: 'auto'                 # авто, 'svd', 'cholesky', 'lsqr', 'sparse_cg'
    
    # Доп. параметры для продвинутых:
    # random_state: 42             # для воспроизводимости (если есть)
  
  # ---------- LASSO (L1-регуляризация) ----------
  lasso:
    enabled: true
    alpha: 0.01                    # обычно меньше, чем для ridge
    fit_intercept: true
    positive: false
    max_iter: 1000
    tol: 0.0001
    selection: 'cyclic'            # 'cyclic' или 'random' (циклический или случайный)
    # warm_start: false            # продолжать обучение с прошлых весов
    
  # ---------- ELASTIC NET (L1 + L2) ----------
  elastic:
    enabled: true
    alpha: 0.01                     # общая сила регуляризации
    l1_ratio: 0.5                    # баланс L1/L2 (0 = чистый Ridge, 1 = чистый Lasso)
    fit_intercept: true
    positive: false
    max_iter: 1000
    tol: 0.0001
    selection: 'cyclic'